# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_text-asset_json.json
#   source_etag: W/"68f98531-1d8"
#   source_last_modified: Thu, 23 Oct 2025 01:30:25 GMT

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class TextAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: Annotated[str, Field(description="Text content")]
    language: Annotated[str | None, Field(description="Language code (e.g., 'en', 'es', 'fr')")] = None
