# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_list-creative-formats-request_json.json
#   timestamp: 2025-10-15T00:10:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Type(Enum):
    audio = "audio"
    video = "video"
    display = "display"
    dooh = "dooh"


class AssetType(Enum):
    image = "image"
    video = "video"
    audio = "audio"
    text = "text"
    html = "html"
    javascript = "javascript"
    url = "url"


class ListCreativeFormatsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format_ids: Annotated[
        list[str] | None,
        Field(description="Return only these specific format IDs (e.g., from get_products response)"),
    ] = None
    type: Annotated[
        Type | None, Field(description="Filter by format type (technical categories with distinct requirements)")
    ] = None
    asset_types: Annotated[
        list[AssetType] | None,
        Field(
            description="Filter to formats that include these asset types. For third-party tags, search for 'html' or 'javascript'. E.g., ['image', 'text'] returns formats with images and text, ['javascript'] returns formats accepting JavaScript tags."
        ),
    ] = None
    max_width: Annotated[
        int | None,
        Field(
            description="Maximum width in pixels (inclusive). Returns formats with width <= this value. Omit for responsive/fluid formats."
        ),
    ] = None
    max_height: Annotated[
        int | None,
        Field(
            description="Maximum height in pixels (inclusive). Returns formats with height <= this value. Omit for responsive/fluid formats."
        ),
    ] = None
    min_width: Annotated[
        int | None,
        Field(description="Minimum width in pixels (inclusive). Returns formats with width >= this value."),
    ] = None
    min_height: Annotated[
        int | None,
        Field(description="Minimum height in pixels (inclusive). Returns formats with height >= this value."),
    ] = None
    is_responsive: Annotated[
        bool | None,
        Field(
            description="Filter for responsive formats that adapt to container size. When true, returns formats without fixed dimensions."
        ),
    ] = None
    name_search: Annotated[
        str | None, Field(description="Search for formats by name (case-insensitive partial match)")
    ] = None
