# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_sync-creatives-response_json.json
#   schema_hash: fe04cdcbc5da

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Action(Enum):
    created = "created"
    updated = "updated"
    unchanged = "unchanged"
    failed = "failed"
    deleted = "deleted"


class Creative(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    creative_id: Annotated[str, Field(description="Creative ID from the request")]
    action: Annotated[Action, Field(description="Action taken for this creative")]
    platform_id: Annotated[str | None, Field(description="Platform-specific ID assigned to the creative")] = None
    changes: Annotated[
        list[str] | None, Field(description="Field names that were modified (only present when action='updated')")
    ] = None
    errors: Annotated[
        list[str] | None, Field(description="Validation or processing errors (only present when action='failed')")
    ] = None
    warnings: Annotated[list[str] | None, Field(description="Non-fatal warnings about this creative")] = None
    preview_url: Annotated[
        AnyUrl | None, Field(description="Preview URL for generative creatives (only present for generative formats)")
    ] = None
    expires_at: Annotated[
        AwareDatetime | None,
        Field(description="ISO 8601 timestamp when preview link expires (only present when preview_url exists)"),
    ] = None
    assigned_to: Annotated[
        list[str] | None,
        Field(
            description="Package IDs this creative was successfully assigned to (only present when assignments were requested)"
        ),
    ] = None
    assignment_errors: Annotated[
        dict[str, str] | None,
        Field(description="Assignment errors by package ID (only present when assignment failures occurred)"),
    ] = None


class SyncCreativesResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dry_run: Annotated[bool | None, Field(description="Whether this was a dry run (no actual changes made)")] = None
    creatives: Annotated[
        list[Creative],
        Field(
            description="Results for each creative processed. Items with action='failed' indicate per-item validation/processing failures, not operation-level failures."
        ),
    ]


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        str | None, Field(description="Field path associated with the error (e.g., 'packages[0].targeting')")
    ] = None
    suggestion: Annotated[str | None, Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[float | None, Field(description="Seconds to wait before retrying the operation", ge=0.0)] = (
        None
    )
    details: Annotated[Any | None, Field(description="Additional task-specific error details")] = None


class SyncCreativesResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: Annotated[
        list[Error],
        Field(
            description="Operation-level errors that prevented processing any creatives (e.g., authentication failure, service unavailable, invalid request format)",
            min_length=1,
        ),
    ]


class SyncCreativesResponse(RootModel[SyncCreativesResponse1 | SyncCreativesResponse2]):
    root: Annotated[
        SyncCreativesResponse1 | SyncCreativesResponse2,
        Field(
            description="Response from creative sync operation. Returns either per-creative results (best-effort processing) OR operation-level errors (complete failure). This enforces atomic semantics at the operation level while allowing per-item failures within successful operations.",
            title="Sync Creatives Response",
        ),
    ]
