# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_deployment_json.json
#   schema_hash: fbb5805cd025

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ActivationKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[Literal["segment_id"], Field(description="Segment ID based targeting")]
    segment_id: Annotated[
        str, Field(description="The platform-specific segment identifier to use in campaign targeting")
    ]


class ActivationKey1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[Literal["key_value"], Field(description="Key-value pair based targeting")]
    key: Annotated[str, Field(description="The targeting parameter key")]
    value: Annotated[str, Field(description="The targeting parameter value")]


class Deployment1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["platform"], Field(description="Discriminator indicating this is a platform-based deployment")
    ]
    platform: Annotated[str, Field(description="Platform identifier for DSPs")]
    account: Annotated[str | None, Field(description="Account identifier if applicable")] = None
    is_live: Annotated[bool, Field(description="Whether signal is currently active on this destination")]
    activation_key: Annotated[
        ActivationKey | ActivationKey1 | None,
        Field(
            description="Universal identifier for using a signal on a destination platform. Can be either a segment ID or a key-value pair depending on the platform's targeting mechanism.",
            title="Activation Key",
        ),
    ] = None
    estimated_activation_duration_minutes: Annotated[
        float | None,
        Field(description="Estimated time to activate if not live, or to complete activation if in progress", ge=0.0),
    ] = None
    deployed_at: Annotated[
        AwareDatetime | None, Field(description="Timestamp when activation completed (if is_live=true)")
    ] = None


class Deployment2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["agent"], Field(description="Discriminator indicating this is an agent URL-based deployment")
    ]
    agent_url: Annotated[AnyUrl, Field(description="URL identifying the destination agent")]
    account: Annotated[str | None, Field(description="Account identifier if applicable")] = None
    is_live: Annotated[bool, Field(description="Whether signal is currently active on this destination")]
    activation_key: Annotated[
        Any | None, Field(description="Circular reference to /schemas/v1/core/activation-key.json")
    ] = None
    estimated_activation_duration_minutes: Annotated[
        float | None,
        Field(description="Estimated time to activate if not live, or to complete activation if in progress", ge=0.0),
    ] = None
    deployed_at: Annotated[
        AwareDatetime | None, Field(description="Timestamp when activation completed (if is_live=true)")
    ] = None


class Deployment(RootModel[Deployment1 | Deployment2]):
    root: Annotated[
        Deployment1 | Deployment2,
        Field(
            description="A signal deployment to a specific destination platform with activation status and key",
            title="Deployment",
        ),
    ]
