# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_sub-asset_json.json
#   schema_hash: 15880e81b818

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class SubAsset1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_kind: Annotated[
        Literal["media"], Field(description="Discriminator indicating this is a media asset with content_uri")
    ]
    asset_type: Annotated[
        str, Field(description="Type of asset. Common types: thumbnail_image, product_image, featured_image, logo")
    ]
    asset_id: Annotated[str, Field(description="Unique identifier for the asset within the creative")]
    content_uri: Annotated[AnyUrl, Field(description="URL for media assets (images, videos, etc.)")]


class SubAsset2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_kind: Annotated[
        Literal["text"], Field(description="Discriminator indicating this is a text asset with content")
    ]
    asset_type: Annotated[
        str,
        Field(
            description="Type of asset. Common types: headline, body_text, cta_text, price_text, sponsor_name, author_name, click_url"
        ),
    ]
    asset_id: Annotated[str, Field(description="Unique identifier for the asset within the creative")]
    content: Annotated[
        str | list[str],
        Field(description="Text content for text-based assets like headlines, body text, CTA text, etc."),
    ]


class SubAsset(RootModel[SubAsset1 | SubAsset2]):
    root: Annotated[
        SubAsset1 | SubAsset2,
        Field(
            description="Sub-asset for multi-asset creative formats, including carousel images and native ad template variables",
            title="Sub-Asset",
        ),
    ]
