# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_package-status_json.json
#   source_etag: W/"68f98531-1c4"
#   source_last_modified: Thu, 23 Oct 2025 01:30:25 GMT

from __future__ import annotations

from enum import Enum


class PackageStatus(Enum):
    draft = "draft"
    active = "active"
    paused = "paused"
    completed = "completed"
