# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_creative-status_json.json
#   source_etag: W/"68f98531-237"
#   source_last_modified: Thu, 23 Oct 2025 01:30:25 GMT

from __future__ import annotations

from enum import Enum


class CreativeStatus(Enum):
    processing = "processing"
    approved = "approved"
    rejected = "rejected"
    pending_review = "pending_review"
