# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_provide-performance-feedback-response_json.json
#   schema_hash: 3ead55dda93e

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ProvidePerformanceFeedbackResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    success: Annotated[Literal[True], Field(description="Whether the performance feedback was successfully received")]


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        str | None, Field(description="Field path associated with the error (e.g., 'packages[0].targeting')")
    ] = None
    suggestion: Annotated[str | None, Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[float | None, Field(description="Seconds to wait before retrying the operation", ge=0.0)] = (
        None
    )
    details: Annotated[Any | None, Field(description="Additional task-specific error details")] = None


class ProvidePerformanceFeedbackResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: Annotated[
        list[Error],
        Field(
            description="Array of errors explaining why feedback was rejected (e.g., invalid measurement period, missing campaign data)",
            min_length=1,
        ),
    ]


class ProvidePerformanceFeedbackResponse(
    RootModel[ProvidePerformanceFeedbackResponse1 | ProvidePerformanceFeedbackResponse2]
):
    root: Annotated[
        ProvidePerformanceFeedbackResponse1 | ProvidePerformanceFeedbackResponse2,
        Field(
            description="Response payload for provide_performance_feedback task. Returns either success confirmation OR error information, never both.",
            title="Provide Performance Feedback Response",
        ),
    ]
