# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_creative-assignment_json.json
#   source_etag: W/"68f98531-462"
#   source_last_modified: Thu, 23 Oct 2025 01:30:25 GMT

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class CreativeAssignment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    creative_id: Annotated[str, Field(description="Unique identifier for the creative")]
    weight: Annotated[float | None, Field(description="Delivery weight for this creative", ge=0.0, le=100.0)] = None
    placement_ids: Annotated[
        list[str] | None,
        Field(
            description="Optional array of placement IDs where this creative should run. When omitted, the creative runs on all placements in the package. References placement_id values from the product's placements array.",
            min_length=1,
        ),
    ] = None
