# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_task-type_json.json
#   schema_hash: 1b5e8192ee33

from __future__ import annotations

from enum import Enum


class TaskType(Enum):
    create_media_buy = "create_media_buy"
    update_media_buy = "update_media_buy"
    sync_creatives = "sync_creatives"
    activate_signal = "activate_signal"
    get_signals = "get_signals"
