# generated by datamodel-codegen:
#   filename:  _schemas_v1_signals_get-signals-request_json.json
#   schema_hash: ee6b178f1bb1

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Destinations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["platform"], Field(description="Discriminator indicating this is a platform-based destination")
    ]
    platform: Annotated[str, Field(description="Platform identifier for DSPs (e.g., 'the-trade-desk', 'amazon-dsp')")]
    account: Annotated[str | None, Field(description="Optional account identifier on the platform")] = None


class Destinations3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["agent"], Field(description="Discriminator indicating this is an agent URL-based destination")
    ]
    agent_url: Annotated[AnyUrl, Field(description="URL identifying the destination agent (for sales agents, etc.)")]
    account: Annotated[str | None, Field(description="Optional account identifier on the agent")] = None


class Country(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Z]{2}$")]


class DeliverTo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    destinations: Annotated[
        list[Destinations | Destinations3],
        Field(
            description="List of destination platforms (DSPs, sales agents, etc.). If the authenticated caller matches one of these destinations, activation keys will be included in the response.",
            min_length=1,
        ),
    ]
    countries: Annotated[list[Country], Field(description="Countries where signals will be used (ISO codes)")]


class CatalogType(Enum):
    marketplace = "marketplace"
    custom = "custom"
    owned = "owned"


class Filters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    catalog_types: Annotated[list[CatalogType] | None, Field(description="Filter by catalog type")] = None
    data_providers: Annotated[list[str] | None, Field(description="Filter by specific data providers")] = None
    max_cpm: Annotated[float | None, Field(description="Maximum CPM price filter", ge=0.0)] = None
    min_coverage_percentage: Annotated[
        float | None, Field(description="Minimum coverage requirement", ge=0.0, le=100.0)
    ] = None


class GetSignalsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    signal_spec: Annotated[str, Field(description="Natural language description of the desired signals")]
    deliver_to: Annotated[DeliverTo, Field(description="Destination platforms where signals need to be activated")]
    filters: Annotated[Filters | None, Field(description="Filters to refine results")] = None
    max_results: Annotated[int | None, Field(description="Maximum number of results to return", ge=1)] = None
