# generated by datamodel-codegen:
#   filename:  _schemas_v1_signals_get-signals-response_json.json
#   schema_hash: 44932adaea84

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class SignalType(Enum):
    marketplace = "marketplace"
    custom = "custom"
    owned = "owned"


class ActivationKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[Literal["segment_id"], Field(description="Segment ID based targeting")]
    segment_id: Annotated[
        str, Field(description="The platform-specific segment identifier to use in campaign targeting")
    ]


class ActivationKey5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[Literal["key_value"], Field(description="Key-value pair based targeting")]
    key: Annotated[str, Field(description="The targeting parameter key")]
    value: Annotated[str, Field(description="The targeting parameter value")]


class Deployments(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["platform"], Field(description="Discriminator indicating this is a platform-based deployment")
    ]
    platform: Annotated[str, Field(description="Platform identifier for DSPs")]
    account: Annotated[str | None, Field(description="Account identifier if applicable")] = None
    is_live: Annotated[bool, Field(description="Whether signal is currently active on this destination")]
    activation_key: Annotated[
        ActivationKey | ActivationKey5 | None,
        Field(
            description="Universal identifier for using a signal on a destination platform. Can be either a segment ID or a key-value pair depending on the platform's targeting mechanism.",
            title="Activation Key",
        ),
    ] = None
    estimated_activation_duration_minutes: Annotated[
        float | None,
        Field(description="Estimated time to activate if not live, or to complete activation if in progress", ge=0.0),
    ] = None
    deployed_at: Annotated[
        AwareDatetime | None, Field(description="Timestamp when activation completed (if is_live=true)")
    ] = None


class Deployments3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["agent"], Field(description="Discriminator indicating this is an agent URL-based deployment")
    ]
    agent_url: Annotated[AnyUrl, Field(description="URL identifying the destination agent")]
    account: Annotated[str | None, Field(description="Account identifier if applicable")] = None
    is_live: Annotated[bool, Field(description="Whether signal is currently active on this destination")]
    activation_key: Annotated[
        Any | None, Field(description="Circular reference to /schemas/v1/core/activation-key.json")
    ] = None
    estimated_activation_duration_minutes: Annotated[
        float | None,
        Field(description="Estimated time to activate if not live, or to complete activation if in progress", ge=0.0),
    ] = None
    deployed_at: Annotated[
        AwareDatetime | None, Field(description="Timestamp when activation completed (if is_live=true)")
    ] = None


class Pricing(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cpm: Annotated[float, Field(description="Cost per thousand impressions", ge=0.0)]
    currency: Annotated[str, Field(description="Currency code", pattern="^[A-Z]{3}$")]


class Signal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    signal_agent_segment_id: Annotated[str, Field(description="Unique identifier for the signal")]
    name: Annotated[str, Field(description="Human-readable signal name")]
    description: Annotated[str, Field(description="Detailed signal description")]
    signal_type: Annotated[SignalType, Field(description="Type of signal")]
    data_provider: Annotated[str, Field(description="Name of the data provider")]
    coverage_percentage: Annotated[float, Field(description="Percentage of audience coverage", ge=0.0, le=100.0)]
    deployments: Annotated[list[Deployments | Deployments3], Field(description="Array of destination deployments")]
    pricing: Annotated[Pricing, Field(description="Pricing information")]


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        str | None, Field(description="Field path associated with the error (e.g., 'packages[0].targeting')")
    ] = None
    suggestion: Annotated[str | None, Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[float | None, Field(description="Seconds to wait before retrying the operation", ge=0.0)] = (
        None
    )
    details: Annotated[Any | None, Field(description="Additional task-specific error details")] = None


class GetSignalsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    signals: Annotated[list[Signal], Field(description="Array of matching signals")]
    errors: Annotated[
        list[Error] | None,
        Field(description="Task-specific errors and warnings (e.g., signal discovery or pricing issues)"),
    ] = None
