# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_start-timing_json.json
#   source_etag: W/"68f98531-1da"
#   source_last_modified: Thu, 23 Oct 2025 01:30:25 GMT

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, Field, RootModel


class StartTiming(RootModel[str | AwareDatetime]):
    root: Annotated[
        str | AwareDatetime,
        Field(description="Campaign start timing: 'asap' or ISO 8601 date-time", title="Start Timing"),
    ]
