# generated by datamodel-codegen:
#   filename:  _schemas_v1_signals_activate-signal-request_json.json
#   schema_hash: f69d3edac82e

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class Destinations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["platform"], Field(description="Discriminator indicating this is a platform-based destination")
    ]
    platform: Annotated[str, Field(description="Platform identifier for DSPs (e.g., 'the-trade-desk', 'amazon-dsp')")]
    account: Annotated[str | None, Field(description="Optional account identifier on the platform")] = None


class Destinations1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["agent"], Field(description="Discriminator indicating this is an agent URL-based destination")
    ]
    agent_url: Annotated[AnyUrl, Field(description="URL identifying the destination agent (for sales agents, etc.)")]
    account: Annotated[str | None, Field(description="Optional account identifier on the agent")] = None


class ActivateSignalRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    signal_agent_segment_id: Annotated[str, Field(description="The universal identifier for the signal to activate")]
    destinations: Annotated[
        list[Destinations | Destinations1],
        Field(
            description="Target destination(s) for activation. If the authenticated caller matches one of these destinations, activation keys will be included in the response.",
            min_length=1,
        ),
    ]
