# generated by datamodel-codegen:
#   filename:  _schemas_v1_pricing-options_cpc-option_json.json
#   source_etag: W/"68f98531-48e"
#   source_last_modified: Thu, 23 Oct 2025 01:30:25 GMT

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class CpcPricingOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str, Field(description="Unique identifier for this pricing option within the product (e.g., 'cpc_usd_fixed')")
    ]
    pricing_model: Annotated[Literal["cpc"], Field(description="Cost per click")]
    rate: Annotated[float, Field(description="Fixed CPC rate (cost per click)", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None
