# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_creative-asset_json.json
#   timestamp: 2025-10-15T00:10:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class FormatId(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent_url: Annotated[
        AnyUrl,
        Field(
            description="URL of the agent that defines this format (e.g., 'https://creatives.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats)"
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="Format identifier within the agent's namespace (e.g., 'display_300x250', 'video_standard_30s')",
            pattern="^[a-zA-Z0-9_-]+$",
        ),
    ]


class Assets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["image"]
    url: Annotated[AnyUrl, Field(description="URL to the image asset")]
    width: Annotated[int | None, Field(description="Image width in pixels", ge=1)] = None
    height: Annotated[int | None, Field(description="Image height in pixels", ge=1)] = None
    format: Annotated[str | None, Field(description="Image file format (jpg, png, gif, webp, etc.)")] = None
    alt_text: Annotated[str | None, Field(description="Alternative text for accessibility")] = None


class Assets1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["video"]
    url: Annotated[AnyUrl, Field(description="URL to the video asset")]
    width: Annotated[int | None, Field(description="Video width in pixels", ge=1)] = None
    height: Annotated[int | None, Field(description="Video height in pixels", ge=1)] = None
    duration_ms: Annotated[int | None, Field(description="Video duration in milliseconds", ge=0)] = None
    format: Annotated[str | None, Field(description="Video file format (mp4, webm, mov, etc.)")] = None
    bitrate_kbps: Annotated[int | None, Field(description="Video bitrate in kilobits per second", ge=1)] = None


class Assets2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["audio"]
    url: Annotated[AnyUrl, Field(description="URL to the audio asset")]
    duration_ms: Annotated[int | None, Field(description="Audio duration in milliseconds", ge=0)] = None
    format: Annotated[str | None, Field(description="Audio file format (mp3, wav, aac, etc.)")] = None
    bitrate_kbps: Annotated[int | None, Field(description="Audio bitrate in kilobits per second", ge=1)] = None


class Assets3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["text"]
    content: Annotated[str, Field(description="Text content")]
    max_length: Annotated[int | None, Field(description="Maximum character length constraint", ge=1)] = None
    language: Annotated[str | None, Field(description="Language code (e.g., 'en', 'es', 'fr')")] = None


class Assets4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["html"]
    content: Annotated[str, Field(description="HTML content")]
    version: Annotated[str | None, Field(description="HTML version (e.g., 'HTML5')")] = None


class Assets5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["css"]
    content: Annotated[str, Field(description="CSS content")]
    media: Annotated[str | None, Field(description="CSS media query context (e.g., 'screen', 'print')")] = None


class ModuleType(Enum):
    esm = "esm"
    commonjs = "commonjs"
    script = "script"


class Assets6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["javascript"]
    content: Annotated[str, Field(description="JavaScript content")]
    module_type: Annotated[ModuleType | None, Field(description="JavaScript module type")] = None


class VastVersion(Enum):
    field_2_0 = "2.0"
    field_3_0 = "3.0"
    field_4_0 = "4.0"
    field_4_1 = "4.1"
    field_4_2 = "4.2"


class TrackingEvent(Enum):
    start = "start"
    first_quartile = "firstQuartile"
    midpoint = "midpoint"
    third_quartile = "thirdQuartile"
    complete = "complete"
    impression = "impression"
    click = "click"
    pause = "pause"
    resume = "resume"
    skip = "skip"
    mute = "mute"
    unmute = "unmute"
    fullscreen = "fullscreen"
    exit_fullscreen = "exitFullscreen"
    player_expand = "playerExpand"
    player_collapse = "playerCollapse"


class Assets7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["vast"]
    url: Annotated[AnyUrl, Field(description="URL endpoint that returns VAST XML")]
    content: Annotated[str | None, Field(description="Inline VAST XML content")] = None
    vast_version: Annotated[VastVersion | None, Field(description="VAST specification version")] = None
    vpaid_enabled: Annotated[
        bool | None, Field(description="Whether VPAID (Video Player-Ad Interface Definition) is supported")
    ] = None
    max_wrapper_depth: Annotated[
        int | None, Field(description="Maximum allowed wrapper/redirect depth", ge=0, le=10)
    ] = None
    duration_ms: Annotated[
        int | None, Field(description="Expected video duration in milliseconds (if known)", ge=0)
    ] = None
    tracking_events: Annotated[
        list[TrackingEvent] | None, Field(description="Tracking events supported by this VAST tag")
    ] = None


class Assets8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["vast"]
    url: Annotated[AnyUrl | None, Field(description="URL endpoint that returns VAST XML")] = None
    content: Annotated[str, Field(description="Inline VAST XML content")]
    vast_version: Annotated[VastVersion | None, Field(description="VAST specification version")] = None
    vpaid_enabled: Annotated[
        bool | None, Field(description="Whether VPAID (Video Player-Ad Interface Definition) is supported")
    ] = None
    max_wrapper_depth: Annotated[
        int | None, Field(description="Maximum allowed wrapper/redirect depth", ge=0, le=10)
    ] = None
    duration_ms: Annotated[
        int | None, Field(description="Expected video duration in milliseconds (if known)", ge=0)
    ] = None
    tracking_events: Annotated[
        list[TrackingEvent] | None, Field(description="Tracking events supported by this VAST tag")
    ] = None


class DaastVersion(Enum):
    field_1_0 = "1.0"
    field_1_1 = "1.1"


class TrackingEvent6(Enum):
    start = "start"
    first_quartile = "firstQuartile"
    midpoint = "midpoint"
    third_quartile = "thirdQuartile"
    complete = "complete"
    impression = "impression"
    pause = "pause"
    resume = "resume"
    skip = "skip"
    mute = "mute"
    unmute = "unmute"


class Assets9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["daast"]
    url: Annotated[AnyUrl, Field(description="URL endpoint that returns DAAST XML")]
    content: Annotated[str | None, Field(description="Inline DAAST XML content")] = None
    daast_version: Annotated[DaastVersion | None, Field(description="DAAST specification version")] = None
    duration_ms: Annotated[
        int | None, Field(description="Expected audio duration in milliseconds (if known)", ge=0)
    ] = None
    tracking_events: Annotated[
        list[TrackingEvent6] | None, Field(description="Tracking events supported by this DAAST tag")
    ] = None
    companion_ads: Annotated[bool | None, Field(description="Whether companion display ads are included")] = None


class Assets10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["daast"]
    url: Annotated[AnyUrl | None, Field(description="URL endpoint that returns DAAST XML")] = None
    content: Annotated[str, Field(description="Inline DAAST XML content")]
    daast_version: Annotated[DaastVersion | None, Field(description="DAAST specification version")] = None
    duration_ms: Annotated[
        int | None, Field(description="Expected audio duration in milliseconds (if known)", ge=0)
    ] = None
    tracking_events: Annotated[
        list[TrackingEvent6] | None, Field(description="Tracking events supported by this DAAST tag")
    ] = None
    companion_ads: Annotated[bool | None, Field(description="Whether companion display ads are included")] = None


class Colors(BaseModel):
    primary: str | None = None
    secondary: str | None = None
    accent: str | None = None


class Assets11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["promoted_offerings"]
    url: Annotated[
        AnyUrl | None, Field(description="URL of the advertiser's brand or offering (e.g., https://retailer.com)")
    ] = None
    colors: Annotated[Colors | None, Field(description="Brand colors")] = None
    fonts: Annotated[list[str] | None, Field(description="Brand fonts")] = None
    tone: Annotated[str | None, Field(description="Brand tone/voice")] = None


class Assets12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["url"]
    url: Annotated[AnyUrl, Field(description="URL reference")]
    description: Annotated[str | None, Field(description="Description of what this URL points to")] = None


class Input(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(description="Human-readable name for this preview variant")]
    macros: Annotated[dict[str, str] | None, Field(description="Macro values to apply for this preview")] = None
    context_description: Annotated[
        str | None, Field(description="Natural language description of the context for AI-generated content")
    ] = None


class CreativeAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    creative_id: Annotated[str, Field(description="Unique identifier for the creative")]
    name: Annotated[str, Field(description="Human-readable creative name")]
    format_id: Annotated[
        FormatId, Field(description="Structured format identifier with agent URL and format name", title="Format ID")
    ]
    assets: Annotated[
        dict[
            str,
            Assets | Assets1 | Assets2 | Assets3 | Assets4 | Assets5 | Assets6 | Assets7 | Assets8 | Assets9 | Assets10 | Assets11 | Assets12,
        ],
        Field(description="Assets required by the format, keyed by asset_role"),
    ]
    inputs: Annotated[
        list[Input] | None,
        Field(description="Preview contexts for generative formats - defines what scenarios to generate previews for"),
    ] = None
    tags: Annotated[list[str] | None, Field(description="User-defined tags for organization and searchability")] = (
        None
    )
    approved: Annotated[
        bool | None,
        Field(
            description="For generative creatives: set to true to approve and finalize, false to request regeneration with updated assets/message. Omit for non-generative creatives."
        ),
    ] = None
