# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_pacing_json.json
#   source_etag: W/"68f98531-1f7"
#   source_last_modified: Thu, 23 Oct 2025 01:30:25 GMT

from __future__ import annotations

from enum import Enum


class Pacing(Enum):
    even = "even"
    asap = "asap"
    front_loaded = "front_loaded"
