# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_destination_json.json
#   schema_hash: d9c20252e27a

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Destination1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["platform"], Field(description="Discriminator indicating this is a platform-based destination")
    ]
    platform: Annotated[str, Field(description="Platform identifier for DSPs (e.g., 'the-trade-desk', 'amazon-dsp')")]
    account: Annotated[str | None, Field(description="Optional account identifier on the platform")] = None


class Destination2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["agent"], Field(description="Discriminator indicating this is an agent URL-based destination")
    ]
    agent_url: Annotated[AnyUrl, Field(description="URL identifying the destination agent (for sales agents, etc.)")]
    account: Annotated[str | None, Field(description="Optional account identifier on the agent")] = None


class Destination(RootModel[Destination1 | Destination2]):
    root: Annotated[
        Destination1 | Destination2,
        Field(
            description="A destination platform where signals can be activated (DSP, sales agent, etc.)",
            title="Destination",
        ),
    ]
