# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_delivery-type_json.json
#   source_etag: W/"68f98531-1a0"
#   source_last_modified: Thu, 23 Oct 2025 01:30:25 GMT

from __future__ import annotations

from enum import Enum


class DeliveryType(Enum):
    guaranteed = "guaranteed"
    non_guaranteed = "non_guaranteed"
