# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_pricing-model_json.json
#   source_etag: W/"68f98531-3a1"
#   source_last_modified: Thu, 23 Oct 2025 01:30:25 GMT

from __future__ import annotations

from enum import Enum


class PricingModel(Enum):
    cpm = "cpm"
    vcpm = "vcpm"
    cpc = "cpc"
    cpcv = "cpcv"
    cpv = "cpv"
    cpp = "cpp"
    flat_rate = "flat_rate"
