# generated by datamodel-codegen:
#   filename:  _schemas_v1_signals_activate-signal-response_json.json
#   schema_hash: 3b07170e9c33

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ActivationKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[Literal["segment_id"], Field(description="Segment ID based targeting")]
    segment_id: Annotated[
        str, Field(description="The platform-specific segment identifier to use in campaign targeting")
    ]


class ActivationKey3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[Literal["key_value"], Field(description="Key-value pair based targeting")]
    key: Annotated[str, Field(description="The targeting parameter key")]
    value: Annotated[str, Field(description="The targeting parameter value")]


class Deployments(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["platform"], Field(description="Discriminator indicating this is a platform-based deployment")
    ]
    platform: Annotated[str, Field(description="Platform identifier for DSPs")]
    account: Annotated[str | None, Field(description="Account identifier if applicable")] = None
    is_live: Annotated[bool, Field(description="Whether signal is currently active on this destination")]
    activation_key: Annotated[
        ActivationKey | ActivationKey3 | None,
        Field(
            description="Universal identifier for using a signal on a destination platform. Can be either a segment ID or a key-value pair depending on the platform's targeting mechanism.",
            title="Activation Key",
        ),
    ] = None
    estimated_activation_duration_minutes: Annotated[
        float | None,
        Field(description="Estimated time to activate if not live, or to complete activation if in progress", ge=0.0),
    ] = None
    deployed_at: Annotated[
        AwareDatetime | None, Field(description="Timestamp when activation completed (if is_live=true)")
    ] = None


class Deployments1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["agent"], Field(description="Discriminator indicating this is an agent URL-based deployment")
    ]
    agent_url: Annotated[AnyUrl, Field(description="URL identifying the destination agent")]
    account: Annotated[str | None, Field(description="Account identifier if applicable")] = None
    is_live: Annotated[bool, Field(description="Whether signal is currently active on this destination")]
    activation_key: Annotated[
        Any | None, Field(description="Circular reference to /schemas/v1/core/activation-key.json")
    ] = None
    estimated_activation_duration_minutes: Annotated[
        float | None,
        Field(description="Estimated time to activate if not live, or to complete activation if in progress", ge=0.0),
    ] = None
    deployed_at: Annotated[
        AwareDatetime | None, Field(description="Timestamp when activation completed (if is_live=true)")
    ] = None


class ActivateSignalResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deployments: Annotated[
        list[Deployments | Deployments1], Field(description="Array of deployment results for each destination")
    ]


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        str | None, Field(description="Field path associated with the error (e.g., 'packages[0].targeting')")
    ] = None
    suggestion: Annotated[str | None, Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[float | None, Field(description="Seconds to wait before retrying the operation", ge=0.0)] = (
        None
    )
    details: Annotated[Any | None, Field(description="Additional task-specific error details")] = None


class ActivateSignalResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: Annotated[
        list[Error],
        Field(
            description="Array of errors explaining why activation failed (e.g., platform connectivity issues, signal definition problems, authentication failures)",
            min_length=1,
        ),
    ]


class ActivateSignalResponse(RootModel[ActivateSignalResponse1 | ActivateSignalResponse2]):
    root: Annotated[
        ActivateSignalResponse1 | ActivateSignalResponse2,
        Field(
            description="Response payload for activate_signal task. Returns either complete success data OR error information, never both. This enforces atomic operation semantics - the signal is either fully activated or not activated at all.",
            title="Activate Signal Response",
        ),
    ]
